CREATE TABLE evento (
  id BIGINT NOT NULL AUTO_INCREMENT,
  data VARCHAR(255) NOT NULL,
  horario VARCHAR(255) NOT NULL,
  local VARCHAR(255) NOT NULL,
  nome VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
